# Generated by Django 3.2.5 on 2021-07-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookshop',
            options={'verbose_name': 'Книжный магазин', 'verbose_name_plural': 'Книжные магазины'},
        ),
    ]
