# Generated by Django 3.2.5 on 2021-07-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20210706_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookstore.bookshop'),
        ),
    ]
