# Generated by Django 3.2.5 on 2021-07-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_book_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshop',
            name='address',
        ),
        migrations.AddField(
            model_name='bookshop',
            name='city',
            field=models.CharField(default='Ульяновск', max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookshop',
            name='street',
            field=models.CharField(default='Пусто', max_length=100, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
