# Generated by Django 3.2.5 on 2021-07-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20210706_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Оруэлл', max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
